### ISSUE TITLE
stream output multiple cleanup

### ISSUE THREAD

**Issue by j4k4** [applike/gosoline#111]
instead of residing in `output_configurable_multiple.go` the implementation should be in `output_multiple.go` to be in line with the other outputs.  

The signature of `func NewConfigurableMultiOutput(config cfg.Config, logger mon.Logger, base string) Output` should be `func NewConfigurableMultiOutput(config cfg.Config, logger mon.Logger, outputs []Output) Output` and `func NewConfigurableMultiOutputWithInterfaces(logger mon.Logger, outputs []Output)` to be able to create this output type without configuration file.

To configure this output in `output_configurable.go` a structure of
```go
type multipleOutputConfiguration struct {
	Outputs []string `cfg:"outputs"`
}
```
should be used in conjunction with a 'builder' function ` newMultipleOutputFromConfig` which reads the config and creates the outputs to provide them to the `NewConfigurableMultiOutput` function.

in the end the multiple output should be configured like this:  
```yml
stream:
  output:
    pipeline:
      type: multiple
      outputs: [outputA, outputB]
    outputA:
      type: kinesis
      stream_name: kinesis-stream-a
    outputB:
      type: kinesis
      stream_name: kinesis-stream-b
```
