### ISSUE TITLE
Allow fine grained configuration of kvStores in chain

### ISSUE THREAD

**Issue by ajscholl** [applike/gosoline#352]
Different kvStores in a chain might warrant different configurations. However, right now they share whatever can be configured on the chain config itself. For example, an inMemory store might want to have a shorter ttl than the redis it is reading from (when working with a chain of length 3) because some other process might update the redis and ddb, so the inMemory store might favor a short ttl, but redis can have a longer ttl. This would also make it nicer to specify store-specific configurations in a chain as they don't have to be merged together in a single place.

Example config one could want to write:

```yml

kvstore:
  myStore:
    type: chain
    application: myApp
    missing_cache:
      enabled: true
      maxSize: 1000
      metrics_enabled: false
    elements:
      - type: inMemory
        ttl: 3min
        maxSize: 10000
      - type: redis
        ttl: 1h
      - type: ddb
        metrics_enabled: false
    metrics_enabled: true
```
